---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lakekeeper-encryption-key
  namespace: lakekeeper
spec:
  encryptedData:
    encryptionKey: AgCjX/lIab6kyHb2BycyDBmUhpK5TfPV0jCaLEZ7bJUF108/7GiCACkZLNlOft2nwLfX73rO8UxY5VEhWY52SyWtf74sWeb3icvfk+q7IBHW9orn/QQnMVfp1d9txHoVdL31DF+Cda6akP/unnwzDAHlsufLMmj2S/e0XOB5yTnVW4aoNEPpBaYB/sRE22bz7tO5tpnuVe8RoHkeJYDAkjwxV1XKHSaGLDYw3XOpAy8LTMleILmI0Tr1IMdfTPoolYtsZEfmvJLGxIRwB2TI3dNIKGpGI0SfuCXQKUKCMlryLyZc6ILPXwnX8Un3TftYFvC4q/4+yuHkadxZN8XqejbQ69szGNJrhUENa8cTYNYYSNWtRwRrJPWThMqNlOoH1ZuNCiaZvNR8wDgoYVtXZyc69OqmVhJCFJt3laFzqq5CFXAps6WSPRuom9cH7SPXtYVZkztMRFIB6b6yWaD67BejjQpbWq8CDJvjTCDOn8njI6IA1roRid9D7QXu0yRgSuA8MWMcq3Hu+dpb20+DVB1GQaqLp5ZDR0570QG4zb2182oonz/tF4P5/LKwO+sv2OxeA6hLRevGI4m2s2IHvN1NS+hZhdBjLJox1cF6vVNtU2B80qRPHDSFh9L8QMXDAhjqCNZpmW9UZ1fqc2Q34j64Tk5yb+giNLqEvc/z407r89iTVF84LFZtm6Z4QvR+fzGQi2F5Kn0JIXdaWyahQbWvLvz7JAD4MMgi0PDqBuDyDJCp0xlWP+0OM3KGJkB3kKeHUgC2CANn2wME1V+Uto6i
  template:
    metadata:
      creationTimestamp: null
      name: lakekeeper-encryption-key
      namespace: lakekeeper
