# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genericmap.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'genericmap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10genericmap.proto\x12\ngenericmap\x1a\x19google/protobuf/any.proto\"0\n\x04\x46low\x12(\n\ngenericMap\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x10\n\x0e\x43ollectorReply2C\n\tCollector\x12\x36\n\x04Send\x12\x10.genericmap.Flow\x1a\x1a.genericmap.CollectorReply\"\x00\x42\x0eZ\x0c./genericmapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genericmap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./genericmap'
  _globals['_FLOW']._serialized_start=59
  _globals['_FLOW']._serialized_end=107
  _globals['_COLLECTORREPLY']._serialized_start=109
  _globals['_COLLECTORREPLY']._serialized_end=125
  _globals['_COLLECTOR']._serialized_start=127
  _globals['_COLLECTOR']._serialized_end=194
# @@protoc_insertion_point(module_scope)
