apiVersion: apps/v1
kind: Deployment
metadata:
  name: kro
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
        - key: node.kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
