---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBBFBIHyJRthq2rAXvLncC54iLKPf3sUV1b7bedse9Z0B1dvNtUtEUJYB9pU+/3WFgCe5jDc4IaCqikXjPXuTl89yIdlK4iKOvr7kkA1rshb3BU53DQsVf6oV88yTYeSl59yfJD4WXu9mlA5mgCYOFNaSNWlYr9QcEIUlquxKhChzDmCGiBKGPX6PxwLrAawzDgPNFocTLiR2/z1dX8c/jbldvuCFe4zk9PXe7Cgv1o9VGxN1mB6ZbAZBsrK6VN/wYW45on83PXbIM8QiVLsQS1W/2M+wrDYBudCNtAy4gJFEV2ViZ44I6F0yzWLzbya3r4cvL6tITj7kpZdy8W2YnkDGsHeBM4nOlenQu1eI6+y7EBqSefjL651eBnZtR+JmV5lqOKBIFeIsf2rJjtKWLlIY73h+9gf7WjZBvkB107lSlUL8N/sfrpvXKzcMl7hdKMAwjl2LuneZ6lxIIEt6NLVZ+mtRGsSxbfBnvQsbctO0IJoD+d0U5zpwtY3LfiuBMpZsWXWpl+c3WkJV2yqwp3n1aTn035isigCBsuaCjw22sTIc5SUztMnbze7aj5J1BUGjLLcViQ0RbUmnn04OzqvkT/L6xE4k4jAJ89ta2y/hQOtPVS60ABEBppVGwY1/OXKbHyBa1ng+F2JNbH8JEq5Tc1uS+33FqSrwC8p76yZHkmjw9iPEB0QYwXsRiII0+fAY63u8QIykve+pn2zVaVrENE/VwEGey3Wk8MVDwn0v5lb3LKvjZk4D7CekcmuNxeilOTdcSZczSeD/0ySb1R
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
