apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keda

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      environment: demo
    includeSelectors: false
